apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - id: "ami-02150f72c202ee9bb"
  role: "KarpenterNodeRole-apdev-eks-cluster"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: apdev-eks-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: apdev-eks-cluster
  tags:
    Name: apdev-app-node
